services:
  tv-service:
    build: .
    container_name: tv-service
    ports:
      - "3444:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 3000
      # App URL Configuration
      NEXT_PUBLIC_APP_URL: ${NEXT_PUBLIC_APP_URL:-https://teve.ahmetfuzunkaya.com}
      # Xtream API Configuration
      XTREAM_API_BASE: ${XTREAM_API_BASE:-http://tgrpro25.xyz:8080/player_api.php}
      XTREAM_USERNAME: ${XTREAM_USERNAME}
      XTREAM_PASSWORD: ${XTREAM_PASSWORD}
      XTREAM_SESSION_COOKIE: ${XTREAM_SESSION_COOKIE:-}
    restart: unless-stopped
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge
    external: true
