services:
  tv-service:
    build: .
    container_name: tv-service
    ports:
      - "3444:3000"
    env_file:
      - .env
    environment:
      NODE_ENV: production
      PORT: 3000
    restart: unless-stopped
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge
    external: true
