services:
  remmina:
    image: lscr.io/linuxserver/remmina:latest
    container_name: remmina
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./data/remmina/config:/config
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "1gb"
    restart: unless-stopped
    networks:
      - proxy-network

  yourls:
    image: tiredofit/yourls:latest
    restart: always
    depends_on:
      - mysql
    networks:
      - proxy-network
    ports:
      - 3444:8080
    environment:
      YOURLS_DB_PASS: AFU
      YOURLS_SITE: https://localhost:3444
      YOURLS_USER: AFU
      YOURLS_PASS: AFU

  pairdrop:
    image: lscr.io/linuxserver/pairdrop:latest
    container_name: pairdrop
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - RATE_LIMIT=false
      - WS_FALLBACK=false
      - RTC_CONFIG=
      - DEBUG_MODE=false
    volumes:
      - ./data/pairdrop/config:/config
    ports:
      - 3002:3000
    restart: unless-stopped
    networks:
      - proxy-network

  luanti:
    image: lscr.io/linuxserver/luanti:latest
    container_name: luanti
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - CLI_ARGS=--gameid devtest
    volumes:
      - ./data/luanti/config:/config/.minetest
    ports:
      - 30000:30000/udp
    restart: unless-stopped
    networks:
      - proxy-network

  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - JELLYFIN_PublishedServerUrl=http://192.168.0.5
    volumes:
      - ./data/jellyfin/config:/config
      - ./data/jellyfin/tvshows:/data/tvshows
      - ./data/jellyfin/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920
      - 7359:7359/udp
      - 1900:1900/udp
    restart: unless-stopped
    networks:
      - proxy-network

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: AFU
      MYSQL_DATABASE: AFU
    volumes:
      - ./data/mysql/db:/var/lib/mysql
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge
    external: true