version: "3.9"

services:
  remmina:
    image: lscr.io/linuxserver/remmina:latest
    container_name: remmina
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./data/remmina/config:/config
    ports:
      - 3000:3000
      - 3001:3001
    shm_size: "1gb"
    restart: unless-stopped
    networks:
      - proxy-network

  kali-linux:
    image: lscr.io/linuxserver/kali-linux:latest
    container_name: kali-linux
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - ./data/kali-linux/config:/config
    ports:
      - 3002:3000
      - 3003:3001
    shm_size: "1gb"
    restart: unless-stopped
    networks:
      - proxy-network

  yourls:
    image: tiredofit/yourls:latest
    restart: always
    depends_on:
      - mysql
    networks:
      - proxy-network
    ports:
      - 8080:8080
    environment:
      YOURLS_DB_PASS: AFU
      YOURLS_SITE: https://localhost:8080
      YOURLS_USER: AFU
      YOURLS_PASS: AFU

  mysql:
    image: mysql:latest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: AFU
      MYSQL_DATABASE: AFU
    volumes:
      - ./data/mysql/db:/var/lib/mysql
    networks:
      - proxy-network

networks:
  proxy-network:
    driver: bridge
    external: true

volumes:
  ./data/mysql/db:
    driver: local
