services:
  stremio:
    image: tsaridas/stremio-docker:latest
    container_name: stremio
    ports:
      - "3579:8080"
      - "11470:11470"
    environment:
      - NO_CORS=1
      - AUTO_SERVER_URL=1
      - TZ=Europe/Istanbul
    volumes:
      - ./stremio-data:/root/.stremio-server
    restart: unless-stopped
    networks:
      - proxy-network

networks:
  proxy-network:
    external: true