version: '3.8'

services:
  # PDF İşleme Aracı
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    container_name: stirling-pdf
    volumes:
      - ./tessdata:/usr/share/tessdata
      - ./configs:/configs
      - ./logs:/logs
      - ./custom-files:/customFiles
    environment:
      - DOCKER_ENABLE_SECURITY=true
      - LANGS=en_US,fr_FR,de_DE
    networks:
      - proxy-network
    restart: unless-stopped

  # RSS Feed Okuyucu
  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    volumes:
      - ./freshrss-data:/config
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
    networks:
      - proxy-network
    restart: unless-stopped

  # Şifre Yöneticisi
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    volumes:
      - ./vaultwarden-data:/data
    environment:
      - WEBSOCKET_ENABLED=true
      - ADMIN_TOKEN=your_admin_token_here
    networks:
      - proxy-network
    restart: unless-stopped

  # URL Kısaltma Servisi
  yourls:
    image: yourls:latest
    container_name: yourls
    volumes:
      - ./yourls-data:/var/www/html
    environment:
      - YOURLS_DB_HOST=yourls-db
      - YOURLS_DB_USER=yourls
      - YOURLS_DB_PASS=yourls_password
      - YOURLS_DB_NAME=yourls
      - YOURLS_SITE=https://your-domain.com
      - YOURLS_USER=admin
      - YOURLS_PASS=admin_password
    depends_on:
      - yourls-db
    networks:
      - proxy-network
    restart: unless-stopped

  # YOURLS Veritabanı
  yourls-db:
    image: mariadb:latest
    container_name: yourls-db
    volumes:
      - ./yourls-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=yourls
      - MYSQL_USER=yourls
      - MYSQL_PASSWORD=yourls_password
    networks:
      - proxy-network
    restart: unless-stopped

  # Blog Platformu
  ghost:
    image: ghost:latest
    container_name: ghost
    volumes:
      - ./ghost-data:/var/lib/ghost/content
    environment:
      - database__client=mysql
      - database__connection__host=ghost-db
      - database__connection__user=ghost
      - database__connection__password=ghost_password
      - database__connection__database=ghost
      - url=https://your-domain.com
    depends_on:
      - ghost-db
    networks:
      - proxy-network
    restart: unless-stopped

  # Ghost Veritabanı
  ghost-db:
    image: mariadb:latest
    container_name: ghost-db
    volumes:
      - ./ghost-db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_DATABASE=ghost
      - MYSQL_USER=ghost
      - MYSQL_PASSWORD=ghost_password
    networks:
      - proxy-network
    restart: unless-stopped

  # Sosyal Medya Link Yöneticisi
  linkstack:
    image: linkstackorg/linkstack:latest
    container_name: linkstack
    volumes:
      - ./linkstack-data:/app/data
    environment:
      - APP_NAME=LinkStack
      - APP_URL=https://your-domain.com
      - APP_ENV=production
      - APP_DEBUG=false
      - DB_CONNECTION=sqlite
      - DB_DATABASE=/app/data/database.sqlite
    networks:
      - proxy-network
    restart: unless-stopped

  # Kanban ve Proje Yönetimi
  wekan:
    image: wekanteam/wekan:latest
    container_name: wekan
    volumes:
      - ./wekan-data:/data
    environment:
      - MONGO_URL=mongodb://wekan-db:27017/wekan
    depends_on:
      - wekan-db
    networks:
      - proxy-network
    restart: unless-stopped

  # Wekan Veritabanı
  wekan-db:
    image: mongo:latest
    container_name: wekan-db
    volumes:
      - ./wekan-db:/data/db
    networks:
      - proxy-network
    restart: unless-stopped

networks:
  proxy-network:
    external: true