services:
  stirling-pdf:
    image: stirlingtools/stirling-pdf:latest
    container_name: stirling-pdf
    volumes:
      - ./data/tessdata:/usr/share/tessdata
      - ./data/configs:/configs
      - ./data/logs:/logs
      - ./data/custom-files:/customFiles
    ports:
      - "8080:8080"
    environment:
      - DOCKER_ENABLE_SECURITY=true
      - LANGS=en_US,fr_FR,de_DE
    networks:
      - proxy-network
    restart: unless-stopped

  freshrss:
    image: lscr.io/linuxserver/freshrss:latest
    container_name: freshrss
    volumes:
      - ./data/freshrss-data:/config
    ports:
      - "8081:80"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Istanbul
    networks:
      - proxy-network
    restart: unless-stopped

  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    volumes:
      - ./data/vaultwarden-data:/data
    ports:
      - "8082:80"
      - "3012:3012"
    environment:
      - WEBSOCKET_ENABLED=true
      - ADMIN_TOKEN=your_admin_token_here
    networks:
      - proxy-network
    restart: unless-stopped

  linkstack:
    image: linkstackorg/linkstack:latest
    container_name: linkstack
    volumes:
      - ./data/linkstack-data:/app/data
    ports:
      - "3133:80"
    environment:
      APP_NAME: LinkStack
      APP_URL: http://localhost:3133
      FORCE_HTTPS: false
      APP_ENV: production
      APP_DEBUG: false
      DB_CONNECTION: sqlite
      DB_DATABASE: /app/data/database.sqlite
      APP_KEY: base64:XfKf4U9T1+0PqYxxcH4U0VjH3PkYt7qg8Yjdz9RyCVE=   # kendi ürettiğin key'i koy
    networks:
      - proxy-network
    restart: unless-stopped

  mongo:
    image: mongo:latest
    container_name: wekan-mongo
    volumes:
      - ./data/mongo_data:/data/db
    restart: unless-stopped

  wekan:
    image: wekanteam/wekan
    container_name: wekan
    depends_on:
      - mongo
    ports:
      - "5555:8080"
    environment:
      MONGO_URL: "mongodb://mongo:27017/wekan"
      ROOT_URL: "http://localhost:8080"
      PORT: "8080"
    restart: unless-stopped

  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: n8n
    ports:
      - "5678:5678"
    environment:
      GENERIC_TIMEZONE: "Europe/Istanbul"
      TZ: "Europe/Istanbul"
      N8N_ENFORCE_SETTINGS_FILE_PERMISSIONS: "true"
      N8N_RUNNERS_ENABLED: "true"
    volumes:
      - n8n_data:/home/node/.n8n
    restart: unless-stopped

volumes:
  n8n_data:
    driver: local

networks:
  proxy-network:
    driver: bridge
    external: true